# Generated by Django 3.2.15 on 2024-02-21 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название дополнения к блюду')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(default='cafe_shtin/static/images/products/null-photo-product.png/', max_length=150, upload_to='addition/', verbose_name='Изображение')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID дополнения к блюду')),
            ],
            options={
                'verbose_name': 'Дополнение',
                'verbose_name_plural': 'Дополнения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AdditionToProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Дополнение для блюда',
                'verbose_name_plural': 'Дополнения для блюда',
                'ordering': ('addition',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Категория блюда')),
                ('sbis_id', models.IntegerField(verbose_name='Идентификатор в СБИС престо')),
            ],
            options={
                'verbose_name': 'Тип блюда',
                'verbose_name_plural': 'Тип блюд',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ItemsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers_order', models.IntegerField(verbose_name='Номер заказа')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Заказ оплачен?')),
                ('payment_type', models.CharField(choices=[('site', 'На сайте'), ('card', 'Картой при получении'), ('cash', 'Наличными при получении')], default='site', max_length=20, verbose_name='Тип оплаты')),
                ('status', models.CharField(default=None, max_length=20, null=True, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование блюда')),
                ('balance', models.IntegerField(default=0, verbose_name='Доступное количество')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('calorie', models.IntegerField(blank=True, null=True, verbose_name='Калории')),
                ('fats', models.IntegerField(blank=True, null=True, verbose_name='Жиры')),
                ('protein', models.IntegerField(blank=True, null=True, verbose_name='Белки')),
                ('carbohydrates', models.IntegerField(blank=True, null=True, verbose_name='Углеводы')),
                ('image', models.ImageField(default='product/null-photo-product.png/', upload_to='product/', verbose_name='Изображение')),
                ('image_code', models.TextField(null=True, verbose_name='Код изображения')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID блюда')),
                ('available', models.BooleanField(default=True, verbose_name='Блюдо доступно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
