# Generated by Django 3.2.15 on 2024-01-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='image',
            field=models.ImageField(default='cafe_shtin/static/images/products/null-photo-product.png/', max_length=150, upload_to='addition/', verbose_name='Изображение'),
        ),
    ]
