# Generated by Django 3.2.15 on 2024-02-21 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.addressuser', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.product', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.orders', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='additiontoproduct',
            name='addition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.addition', verbose_name='Дополнение'),
        ),
        migrations.AddField(
            model_name='additiontoproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.product', verbose_name='Блюдо в которое входит дополнение'),
        ),
    ]
