# Generated by Django 3.2.15 on 2023-08-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additive',
            new_name='Addition',
        ),
        migrations.RenameModel(
            old_name='AdditiveToDish',
            new_name='AdditionToDish',
        ),
    ]
