# Generated by Django 3.2.15 on 2023-08-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20230831_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=150, upload_to='', verbose_name='Сылка на изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.CharField(max_length=40, null=True, verbose_name='UUID блюда'),
        ),
    ]
