# Generated by Django 3.2.15 on 2023-08-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20230831_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.IntegerField(blank=True, null=True, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='UUID блюда'),
        ),
    ]
