# Generated by Django 3.2.15 on 2024-01-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_addition_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_list_id',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Блюдо доступно'),
        ),
        migrations.AddField(
            model_name='product',
            name='calorie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_code',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Код изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='cafe_shtin/static/images/products/null-photo-product.png/', max_length=150, upload_to='product/', verbose_name='Изображение'),
        ),
    ]
