# Generated by Django 3.2.15 on 2023-08-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20230831_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_list_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор прайс-листа'),
        ),
    ]
