# Generated by Django 3.2.15 on 2023-08-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=150, upload_to='product/None', verbose_name='Сылка на изображение'),
        ),
    ]
