# Generated by Django 3.2.15 on 2024-01-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(null=True, unique=True, verbose_name='Идентификатор в СБИС престо'),
        ),
    ]
